WIP: Get multi-line error for heartbeat
For errors where two separate lines of code are related, we want to show
code snippets that span both locations. Then we should fold them when
displaying so that only the relevant lines are showing.

Such is the case when we declare multiple heartbeat methods. The two
slices should share the same source snippet, rather than creating two
individual snippets that are each only one line long.

This is my first stab at getting this working. It works, just needs more
polishing.

The result is an error like this:

error: cannot expose more than one heartbeat method
 --> src/index.ts:4:7
  |
4 |     : Heartbeat {
  |       ^^^^^^^^^ heartbeat first defined here
  |
...
8 | export function heartbeat2(): Heartbeat {
  |                               ^^^^^^^^^ and later defined here
  |

Note: Ideally the origin referenced would point to the second snippet,
not the first.