Touch lib.rs file
When trying to execute `cargo run`, if the lib.rs file isn't present
then the command fails with this error message:

error: failed to parse manifest at `./target/azle/src/Cargo.toml`

Caused by: can't find library `<canister_name>`,
rename file to `src/lib.rs` or specify lib.path

So, to get around that, when we copy over the rust files, we just make a
blank file there that is subsequently overwritten.

TBH, I'm not sure how this was working when we were running this:

```shell
cd target/azle/${rootPath}/azle_generate \
   && cargo run -- <filenames> | rustfmt --edition 2018 > ../src/lib.rs
```

By all accounts it shouldn't have worked but somehow did.